all:
	echo making part a
	gcc Q1_1.c -o Q1_1
	./Q1_1
	echo part a complete
	echo making part b
	gcc Q1_2.c -o Q1_2
	./Q1_2
	echo part 2 complete

Aone:
	echo making part a with semaphores
	gcc Q1_1.c -o Q1_1
	./Q1_1
	echo part a complete

Atwo:
	echo making part a with semaphores
	gcc Q1_1_nosem.c -o Q1_1_nosem
	./Q1_1_nosem
	echo part a without semaphore complete

Bone:
	echo making part b
	gcc Q1_2.c -o Q1_2
	./Q1_2
	echo part 2 complete

clean: 
	rm Q1_1 Q1_2
	echo directory cleaned
