all:
	echo making part a
	gcc Q1_1.c -o Q1_1
	./Q1_1
	echo part a complete
	echo making part b
	gcc Q1_2.c -o Q1_2
	./Q1_2
	echo part 2 complete

one:
	echo making part a
	gcc Q1_1.c -o Q1_1
	./Q1_1
	echo part a complete

two:
	echo making part b
	gcc Q1_2.c -o Q1_2
	./Q1_2
	echo part 2 complete

clean: 
	rm Q1_1 Q1_2
	echo directory cleaned